[build]
  base = "nexcredis-frontend"
  command = "npm run build && npm run export"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
